### PR TITLE
Upgrade android to suport NS3

### PR DESCRIPTION
**Pull request by shanika**
@rhanbIT I just upgraded android support to NS 3.0.0. But didn't touch iOS part. May be this might save your time. I will have a look at iOS part as well if you would like me to. 
Cheers

### CODE REVIEW

**Comment by rhanbIT** [comment]
Thank you very much, it will help me indeed! I will review your PR today! I want to finish the iOS part before doing the 3.0 support !
Cheers @shanika

**Comment by shanika** [comment]
@rhanbIT No worries I can move files to src folder. Just wanted to follow same pattern as other 3.0 plugins.

**Comment by shanika** [comment]
Hi @rhanbIT shall we merge 3.0.0 changes to a separate branch? So you can release 2.x and 3.x version. Since now there are more features in 2.x version developers can use those features if they are continuing to use 2.x version while we port all the features to 3.x. If any one want to use 3.x they can simply use it for android with basic features for android as well. If you like the idea could you please make a new branch so I can cancel this PR and make a new PR to that branch.

**Comment by rhanbIT** [comment]
Hi,
I actually created an other branch with the 2.x support, I will publish patches through it (all 2.x version of the package will be for {N} 2.x). So the changes for the 3.x support will be on the master branch. Ones the support will be fully done I will publish the 3.0 version of the package through the master branch. Normally I should be able to do it tommorow.

**Comment by rhanbIT** [comment]
Hi,

Big thank you for your work, helped me a lot ! I have a few modifications to do for the 3.0 support on iOS but it works well for Android. I should be able to publish the 3.0 version of this package tommorow! 

Cheers from France and thanks again :beers:

**Comment by shanika** [comment]
Awesome that's great news :+1:  :+1:

**Pull request merged**
